# Generated by Django 3.2.15 on 2023-01-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(blank=True, null=True)),
                ('dept_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
    ]
