# Generated by Django 3.2.15 on 2023-01-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConference',
            fields=[
                ('video_conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(blank=True, null=True)),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('video_conference', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'video_conference',
                'managed': False,
            },
        ),
    ]
