# Generated by Django 3.2.15 on 2023-01-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('desi_id', models.IntegerField(blank=True, null=True)),
                ('dep_id', models.IntegerField(blank=True, null=True)),
                ('noof_post', models.IntegerField(blank=True, null=True)),
                ('job_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
    ]
