# Generated by Django 3.2.15 on 2023-01-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('subtitle', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('file_attach', models.TextField(blank=True, null=True)),
                ('st_status', models.CharField(blank=True, max_length=45, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('feed_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('m_task', models.CharField(blank=True, max_length=45, null=True)),
                ('emp_data', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sub_task',
                'managed': False,
            },
        ),
    ]
